# Generated by Django 3.0.7 on 2021-04-22 06:16

import api_.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api_.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
